[package]
name = "tui_prototype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version = "0.19.0" }
crossterm = { version = "0.25" }
rand = "0.8.5"
